version: '3'
services:
  mongo-express:
    image: mongo-express:0.54.0
    ports:
     - "8090:8081"
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongo-db
    depends_on:
     - mongo
  mongo-db:
    image: mongo
    restart: always
    ports:
     - "27017:27017"
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
  temi-app:
    image: 284707391763.dkr.ecr.us-east-2.amazonaws.com/temi-app:1.0
    ports:
     - "3000:3000"
